spring.application.name=gerenciador-tarefas-api

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${GERENCIADOR_TAREFAS_API_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${GERENCIADOR_TAREFAS_API_DB_USER}
spring.datasource.password=${GERENCIADOR_TAREFAS_API_DB_PWD}
spring.jpa.show-sql=${GERENCIADOR_TAREFAS_JPA_SHOW_SQL}

ff4j.web-console.username=${GERENCIADOR_TAREFAS_FF4J_WEB_CONSOLE_USERNAME}
ff4j.web-console.password=${GERENCIADOR_TAREFAS_FF4J_WEB_CONSOLE_PASSWORD}

springdoc.api-docs.path=/api-docs

gerenciador-tarefas.scheduler.task.task-scheduler-cron=${GERENCIADOR_TAREFAS_TASK_SCHEDULER_CRON}